name: Unit tests

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with: 
          version: 2.1.3

      - name: Start poetry shell
        run: poetry env activate

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Install poetry dependencies
        run: poetry install

      - name: Install LaTeX (minimal working set)
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk texlive-latex-base texlive-latex-extra texlive-fonts-recommended

      - name: Run unit tests
        run: poetry run pytest -v

      